replace CaperURI with AutoURI
ENCODE-DCC/croo pull request #15
Opened 2020-03-25 17:47 UTC by leepc12

We have replaced old localization module (Caper's `CaperURI`) with a new one (Autouri's `AutoURI`).

- Deprecated parameters
  - `--http-user` and `--http-password`: Autouri automatically uses `~/.netrc` file for authentication of HTTP URLs. Use `~/.netrc` file.
  - `--use-gsutil-over-aws-s3`: Old module used `aws s3` CLI for S3 files and `gsutil` for GCS files. This parameter is no longer needed since new model uses Python interfaces instead of CLIs.

- Added parameters
  - `--verbose` (`-V`) and `--debug` (`-d`): Prints detailed logs. `verbose >= INFO`, `debug >= DEBUG`.
  - `--use-gsutil-for-s3`: This is different from the deprecated parameter `--use-gsutil-over-aws-s3`. Old loc module used `gsutil` CLI for file transfer between GCS (`gs://`) and any other. But new module optionally uses `gsutil` only for direct file transfer between GCS and S3 (`s3://`). If this flag is turned on `gsutil` will be used only for such direct file transfer.

2020-03-27 22:13 UTC, paul-sud requested changes
A couple of small comments

2020-03-27 22:13 UTC, paul-sud commented on croo/croo.py
> +logger = logging.getLogger('croo')
Usually it is best to call `getLogger` with `__name__`, see https://docs.python.org/3/library/logging.html#logger-objects

```suggestion
logger = logging.getLogger(__name__)
```

2020-03-27 22:13 UTC, paul-sud commented on croo/croo_args.py
> +        raise ValueError('--out-dir is not valid.')
This seems like unreachable code, since `out-dir` defaults to `'.'`: https://github.com/ENCODE-DCC/croo/blob/826ac71fca54920447f9b2b747327b08d4842d97/croo/croo_args.py#L77

2020-03-27 22:13 UTC, p-sud commented on croo/croo_args.py
> +                mapping_path_to_url[k] = v
Probably would be more Pythonic to use the `csv` module here:
```suggestion
import csv
...
        with open(f, newline="") as fp:
            reader = csv.reader(fp, delimiter="\t")
            for line in reader:
                mapping_path_to_url[line[0]] = line[1]
```

2020-03-27 22:54 UTC, leepc12 commented on croo/croo_args.py
> +        raise ValueError('--out-dir is not valid.')
That's right. I will remove it.

2020-03-27 23:05 UTC, paul-sud approved these changes
Looks good now

2020-03-30 20:24 UTC, gabdank approved these changes

2020-03-30 21:02 UTC, merged